; Generated by scripts/build_battle_effects.py; do not edit.
; Gen 2 frames/art: pret/pokecrystal 5beda23ffa505f62e1dad7e3d7c214d1737b3358.
; Timelines adapt the selected effects to Yellow; see the generator.

Gen2EffectTable:
	db THUNDERSHOCK
	dw Gen2Effect_THUNDERSHOCK
	db THUNDERBOLT
	dw Gen2Effect_THUNDERBOLT
	db THUNDER_WAVE
	dw Gen2Effect_THUNDER_WAVE
	db THUNDER
	dw Gen2Effect_THUNDER
	db SCRATCH
	dw Gen2Effect_SCRATCH
	db CUT
	dw Gen2Effect_CUT
	db TACKLE
	dw Gen2Effect_TACKLE
	db QUICK_ATTACK
	dw Gen2Effect_QUICK_ATTACK
	db 0

Gen2Effect_THUNDERSHOCK:
	db 43
	dw Gen2GFX_THUNDERSHOCK
	dw Gen2Timeline_THUNDERSHOCK_0, Gen2Timeline_THUNDERSHOCK_1
Gen2Timeline_THUNDERSHOCK_0:
	db 2, 0
	dw Gen2Frame_0
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_0
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_0
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_0
	db 2, 0
	dw Gen2Frame_1
	db 2, 1
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 2, 0
	dw Gen2Frame_2
	db 2, 0
	dw Gen2Frame_3
	db 2, 0
	dw Gen2Frame_4
	db 2, 0
	dw Gen2Frame_5
	db 0

Gen2Timeline_THUNDERSHOCK_1:
	db 2, 0
	dw Gen2Frame_6
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_6
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_6
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_6
	db 2, 0
	dw Gen2Frame_1
	db 2, 1
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 2, 0
	dw Gen2Frame_7
	db 2, 0
	dw Gen2Frame_8
	db 2, 0
	dw Gen2Frame_9
	db 2, 0
	dw Gen2Frame_10
	db 0

Gen2Effect_THUNDERBOLT:
	db 43
	dw Gen2GFX_THUNDERBOLT
	dw Gen2Timeline_THUNDERBOLT_0, Gen2Timeline_THUNDERBOLT_1
Gen2Timeline_THUNDERBOLT_0:
	db 2, 0
	dw Gen2Frame_11
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_11
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_11
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_11
	db 2, 0
	dw Gen2Frame_1
	db 2, 1
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 1
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 2, 0
	dw Gen2Frame_12
	db 2, 0
	dw Gen2Frame_13
	db 2, 0
	dw Gen2Frame_14
	db 2, 0
	dw Gen2Frame_15
	db 0

Gen2Timeline_THUNDERBOLT_1:
	db 2, 0
	dw Gen2Frame_16
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_16
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_16
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_16
	db 2, 0
	dw Gen2Frame_1
	db 2, 1
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 1
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 2, 0
	dw Gen2Frame_17
	db 2, 0
	dw Gen2Frame_18
	db 2, 0
	dw Gen2Frame_19
	db 2, 0
	dw Gen2Frame_20
	db 0

Gen2Effect_THUNDER_WAVE:
	db 33
	dw Gen2GFX_THUNDER_WAVE
	dw Gen2Timeline_THUNDER_WAVE_0, Gen2Timeline_THUNDER_WAVE_1
Gen2Timeline_THUNDER_WAVE_0:
	db 8, 1
	dw Gen2Frame_21
	db 8, 0
	dw Gen2Frame_22
	db 10, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_23
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_24
	db 2, 0
	dw Gen2Frame_1
	db 0

Gen2Timeline_THUNDER_WAVE_1:
	db 8, 1
	dw Gen2Frame_25
	db 8, 0
	dw Gen2Frame_26
	db 10, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_27
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_28
	db 2, 0
	dw Gen2Frame_1
	db 0

Gen2Effect_THUNDER:
	db 33
	dw Gen2GFX_THUNDER
	dw Gen2Timeline_THUNDER_0, Gen2Timeline_THUNDER_1
Gen2Timeline_THUNDER_0:
	db 2, 1
	dw Gen2Frame_29
	db 2, 0
	dw Gen2Frame_30
	db 2, 0
	dw Gen2Frame_31
	db 10, 0
	dw Gen2Frame_32
	db 2, 1
	dw Gen2Frame_33
	db 2, 0
	dw Gen2Frame_34
	db 2, 0
	dw Gen2Frame_35
	db 10, 0
	dw Gen2Frame_36
	db 2, 1
	dw Gen2Frame_37
	db 2, 0
	dw Gen2Frame_38
	db 2, 0
	dw Gen2Frame_39
	db 16, 0
	dw Gen2Frame_40
	db 16, 0
	dw Gen2Frame_41
	db 10, 0
	dw Gen2Frame_1
	db 0

Gen2Timeline_THUNDER_1:
	db 2, 1
	dw Gen2Frame_42
	db 2, 0
	dw Gen2Frame_43
	db 2, 0
	dw Gen2Frame_44
	db 10, 0
	dw Gen2Frame_45
	db 2, 1
	dw Gen2Frame_46
	db 2, 0
	dw Gen2Frame_47
	db 2, 0
	dw Gen2Frame_48
	db 10, 0
	dw Gen2Frame_49
	db 2, 1
	dw Gen2Frame_50
	db 2, 0
	dw Gen2Frame_51
	db 2, 0
	dw Gen2Frame_52
	db 16, 0
	dw Gen2Frame_53
	db 16, 0
	dw Gen2Frame_54
	db 10, 0
	dw Gen2Frame_1
	db 0

Gen2Effect_SCRATCH:
	db 6
	dw Gen2GFX_SCRATCH
	dw Gen2Timeline_SCRATCH_0, Gen2Timeline_SCRATCH_1
Gen2Timeline_SCRATCH_0:
	db 2, 1
	dw Gen2Frame_55
	db 2, 0
	dw Gen2Frame_56
	db 4, 0
	dw Gen2Frame_57
	db 2, 0
	dw Gen2Frame_58
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_58
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_58
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_58
	db 10, 0
	dw Gen2Frame_1
	db 0

Gen2Timeline_SCRATCH_1:
	db 2, 1
	dw Gen2Frame_59
	db 2, 0
	dw Gen2Frame_60
	db 4, 0
	dw Gen2Frame_61
	db 2, 0
	dw Gen2Frame_62
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_62
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_62
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_62
	db 10, 0
	dw Gen2Frame_1
	db 0

Gen2Effect_CUT:
	db 6
	dw Gen2GFX_CUT
	dw Gen2Timeline_CUT_0, Gen2Timeline_CUT_1
Gen2Timeline_CUT_0:
	db 1, 1
	dw Gen2Frame_63
	db 1, 0
	dw Gen2Frame_64
	db 1, 0
	dw Gen2Frame_65
	db 1, 0
	dw Gen2Frame_66
	db 1, 0
	dw Gen2Frame_67
	db 1, 0
	dw Gen2Frame_68
	db 2, 0
	dw Gen2Frame_69
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_69
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_69
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_69
	db 12, 0
	dw Gen2Frame_1
	db 0

Gen2Timeline_CUT_1:
	db 1, 1
	dw Gen2Frame_70
	db 1, 0
	dw Gen2Frame_71
	db 1, 0
	dw Gen2Frame_72
	db 1, 0
	dw Gen2Frame_73
	db 1, 0
	dw Gen2Frame_74
	db 1, 0
	dw Gen2Frame_75
	db 2, 0
	dw Gen2Frame_76
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_76
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_76
	db 2, 0
	dw Gen2Frame_1
	db 2, 0
	dw Gen2Frame_76
	db 12, 0
	dw Gen2Frame_1
	db 0

Gen2Effect_TACKLE:
	db 26
	dw Gen2GFX_TACKLE
	dw Gen2Timeline_TACKLE_0, Gen2Timeline_TACKLE_1
Gen2Timeline_TACKLE_0:
	db 4, 8
	dw Gen2Frame_1
	db 6, 1
	dw Gen2Frame_77
	db 2, 0
	dw Gen2Frame_1
	db 4, 16
	dw Gen2Frame_1
	db 0

Gen2Timeline_TACKLE_1:
	db 4, 8
	dw Gen2Frame_1
	db 6, 1
	dw Gen2Frame_78
	db 2, 0
	dw Gen2Frame_1
	db 4, 16
	dw Gen2Frame_1
	db 0

Gen2Effect_QUICK_ATTACK:
	db 35
	dw Gen2GFX_QUICK_ATTACK
	dw Gen2Timeline_QUICK_ATTACK_0, Gen2Timeline_QUICK_ATTACK_1
Gen2Timeline_QUICK_ATTACK_0:
	db 1, 3
	dw Gen2Frame_79
	db 1, 0
	dw Gen2Frame_80
	db 1, 0
	dw Gen2Frame_81
	db 9, 0
	dw Gen2Frame_1
	db 6, 1
	dw Gen2Frame_82
	db 2, 0
	dw Gen2Frame_1
	db 16, 4
	dw Gen2Frame_1
	db 0

Gen2Timeline_QUICK_ATTACK_1:
	db 1, 3
	dw Gen2Frame_83
	db 1, 0
	dw Gen2Frame_84
	db 1, 0
	dw Gen2Frame_85
	db 9, 0
	dw Gen2Frame_1
	db 6, 1
	dw Gen2Frame_86
	db 2, 0
	dw Gen2Frame_1
	db 16, 4
	dw Gen2Frame_1
	db 0

Gen2Frame_0:
	db 16
	db $28, $7c, $52, $06
	db $28, $84, $52, $26
	db $30, $7c, $52, $46
	db $30, $84, $52, $66
Gen2Frame_1:
	db 0
Gen2Frame_2:
	db 32
	db $28, $7c, $52, $06
	db $28, $84, $52, $26
	db $30, $7c, $52, $46
	db $30, $84, $52, $66
	db $1c, $80, $41, $07
	db $3c, $80, $41, $67
	db $2c, $70, $40, $07
	db $2c, $90, $40, $67
Gen2Frame_3:
	db 16
	db $1c, $80, $41, $07
	db $3c, $80, $41, $67
	db $2c, $70, $40, $07
	db $2c, $90, $40, $67
Gen2Frame_4:
	db 32
	db $28, $7c, $52, $06
	db $28, $84, $52, $26
	db $30, $7c, $52, $46
	db $30, $84, $52, $66
	db $20, $74, $3f, $27
	db $20, $8c, $3f, $07
	db $38, $74, $3f, $67
	db $38, $8c, $3f, $47
Gen2Frame_5:
	db 16
	db $20, $74, $3f, $27
	db $20, $8c, $3f, $07
	db $38, $74, $3f, $67
	db $38, $8c, $3f, $47
Gen2Frame_6:
	db 16
	db $50, $2c, $52, $26
	db $50, $24, $52, $06
	db $58, $2c, $52, $66
	db $58, $24, $52, $46
Gen2Frame_7:
	db 32
	db $50, $2c, $52, $26
	db $50, $24, $52, $06
	db $58, $2c, $52, $66
	db $58, $24, $52, $46
	db $44, $28, $41, $27
	db $64, $28, $41, $47
	db $54, $38, $40, $27
	db $54, $18, $40, $47
Gen2Frame_8:
	db 16
	db $44, $28, $41, $27
	db $64, $28, $41, $47
	db $54, $38, $40, $27
	db $54, $18, $40, $47
Gen2Frame_9:
	db 32
	db $50, $2c, $52, $26
	db $50, $24, $52, $06
	db $58, $2c, $52, $66
	db $58, $24, $52, $46
	db $48, $34, $3f, $07
	db $48, $1c, $3f, $27
	db $60, $34, $3f, $47
	db $60, $1c, $3f, $67
Gen2Frame_10:
	db 16
	db $48, $34, $3f, $07
	db $48, $1c, $3f, $27
	db $60, $34, $3f, $47
	db $60, $1c, $3f, $67
Gen2Frame_11:
	db 64
	db $20, $74, $53, $06
	db $20, $7c, $54, $06
	db $28, $74, $55, $06
	db $28, $7c, $56, $06
	db $20, $84, $54, $26
	db $20, $8c, $53, $26
	db $28, $84, $56, $26
	db $28, $8c, $55, $26
	db $30, $74, $55, $46
	db $30, $7c, $56, $46
	db $38, $74, $53, $46
	db $38, $7c, $54, $46
	db $30, $84, $56, $66
	db $30, $8c, $55, $66
	db $38, $84, $54, $66
	db $38, $8c, $53, $66
Gen2Frame_12:
	db 80
	db $20, $74, $53, $06
	db $20, $7c, $54, $06
	db $28, $74, $55, $06
	db $28, $7c, $56, $06
	db $20, $84, $54, $26
	db $20, $8c, $53, $26
	db $28, $84, $56, $26
	db $28, $8c, $55, $26
	db $30, $74, $55, $46
	db $30, $7c, $56, $46
	db $38, $74, $53, $46
	db $38, $7c, $54, $46
	db $30, $84, $56, $66
	db $30, $8c, $55, $66
	db $38, $84, $54, $66
	db $38, $8c, $53, $66
	db $18, $80, $41, $07
	db $40, $80, $41, $67
	db $2c, $6c, $40, $07
	db $2c, $94, $40, $67
Gen2Frame_13:
	db 32
	db $18, $80, $41, $07
	db $40, $80, $41, $67
	db $2c, $6c, $40, $07
	db $2c, $94, $40, $67
	db $10, $80, $41, $07
	db $48, $80, $41, $67
	db $2c, $64, $40, $07
	db $2c, $9c, $40, $67
Gen2Frame_14:
	db 80
	db $20, $74, $53, $06
	db $20, $7c, $54, $06
	db $28, $74, $55, $06
	db $28, $7c, $56, $06
	db $20, $84, $54, $26
	db $20, $8c, $53, $26
	db $28, $84, $56, $26
	db $28, $8c, $55, $26
	db $30, $74, $55, $46
	db $30, $7c, $56, $46
	db $38, $74, $53, $46
	db $38, $7c, $54, $46
	db $30, $84, $56, $66
	db $30, $8c, $55, $66
	db $38, $84, $54, $66
	db $38, $8c, $53, $66
	db $1d, $71, $3f, $27
	db $1d, $8f, $3f, $07
	db $3b, $71, $3f, $67
	db $3b, $8f, $3f, $47
Gen2Frame_15:
	db 32
	db $1d, $71, $3f, $27
	db $1d, $8f, $3f, $07
	db $3b, $71, $3f, $67
	db $3b, $8f, $3f, $47
	db $15, $69, $3f, $27
	db $15, $97, $3f, $07
	db $43, $69, $3f, $67
	db $43, $97, $3f, $47
Gen2Frame_16:
	db 64
	db $48, $34, $53, $26
	db $48, $2c, $54, $26
	db $50, $34, $55, $26
	db $50, $2c, $56, $26
	db $48, $24, $54, $06
	db $48, $1c, $53, $06
	db $50, $24, $56, $06
	db $50, $1c, $55, $06
	db $58, $34, $55, $66
	db $58, $2c, $56, $66
	db $60, $34, $53, $66
	db $60, $2c, $54, $66
	db $58, $24, $56, $46
	db $58, $1c, $55, $46
	db $60, $24, $54, $46
	db $60, $1c, $53, $46
Gen2Frame_17:
	db 80
	db $48, $34, $53, $26
	db $48, $2c, $54, $26
	db $50, $34, $55, $26
	db $50, $2c, $56, $26
	db $48, $24, $54, $06
	db $48, $1c, $53, $06
	db $50, $24, $56, $06
	db $50, $1c, $55, $06
	db $58, $34, $55, $66
	db $58, $2c, $56, $66
	db $60, $34, $53, $66
	db $60, $2c, $54, $66
	db $58, $24, $56, $46
	db $58, $1c, $55, $46
	db $60, $24, $54, $46
	db $60, $1c, $53, $46
	db $40, $28, $41, $27
	db $68, $28, $41, $47
	db $54, $3c, $40, $27
	db $54, $14, $40, $47
Gen2Frame_18:
	db 28
	db $40, $28, $41, $27
	db $68, $28, $41, $47
	db $54, $3c, $40, $27
	db $54, $14, $40, $47
	db $38, $28, $41, $27
	db $54, $44, $40, $27
	db $54, $0c, $40, $47
Gen2Frame_19:
	db 80
	db $48, $34, $53, $26
	db $48, $2c, $54, $26
	db $50, $34, $55, $26
	db $50, $2c, $56, $26
	db $48, $24, $54, $06
	db $48, $1c, $53, $06
	db $50, $24, $56, $06
	db $50, $1c, $55, $06
	db $58, $34, $55, $66
	db $58, $2c, $56, $66
	db $60, $34, $53, $66
	db $60, $2c, $54, $66
	db $58, $24, $56, $46
	db $58, $1c, $55, $46
	db $60, $24, $54, $46
	db $60, $1c, $53, $46
	db $45, $37, $3f, $07
	db $45, $19, $3f, $27
	db $63, $37, $3f, $47
	db $63, $19, $3f, $67
Gen2Frame_20:
	db 24
	db $45, $37, $3f, $07
	db $45, $19, $3f, $27
	db $63, $37, $3f, $47
	db $63, $19, $3f, $67
	db $3d, $3f, $3f, $07
	db $3d, $11, $3f, $27
Gen2Frame_21:
	db 16
	db $3c, $74, $31, $47
	db $3c, $7c, $33, $47
	db $3c, $84, $33, $67
	db $3c, $8c, $31, $67
Gen2Frame_22:
	db 64
	db $3c, $74, $31, $47
	db $3c, $7c, $33, $47
	db $3c, $84, $33, $67
	db $3c, $8c, $31, $67
	db $2c, $6c, $3a, $27
	db $2c, $74, $39, $27
	db $2c, $7c, $37, $07
	db $2c, $84, $38, $07
	db $2c, $8c, $39, $07
	db $2c, $94, $3a, $07
	db $34, $6c, $32, $27
	db $34, $74, $31, $27
	db $34, $7c, $3d, $07
	db $34, $84, $3e, $07
	db $34, $8c, $31, $07
	db $34, $94, $32, $07
Gen2Frame_23:
	db 104
	db $3c, $74, $31, $47
	db $3c, $7c, $33, $47
	db $3c, $84, $33, $67
	db $3c, $8c, $31, $67
	db $2c, $6c, $3a, $27
	db $2c, $74, $39, $27
	db $2c, $7c, $37, $07
	db $2c, $84, $38, $07
	db $2c, $8c, $39, $07
	db $2c, $94, $3a, $07
	db $34, $6c, $32, $27
	db $34, $74, $31, $27
	db $34, $7c, $3d, $07
	db $34, $84, $3e, $07
	db $34, $8c, $31, $07
	db $34, $94, $32, $07
	db $1c, $74, $31, $07
	db $1c, $7c, $33, $07
	db $1c, $84, $33, $27
	db $1c, $8c, $31, $27
	db $24, $6c, $34, $27
	db $24, $74, $33, $27
	db $24, $7c, $35, $07
	db $24, $84, $36, $07
	db $24, $8c, $33, $07
	db $24, $94, $34, $07
Gen2Frame_24:
	db 104
	db $1c, $74, $31, $07
	db $1c, $7c, $33, $07
	db $1c, $84, $33, $27
	db $1c, $8c, $31, $27
	db $24, $70, $31, $07
	db $24, $78, $32, $07
	db $24, $7c, $36, $27
	db $24, $84, $35, $27
	db $24, $88, $32, $27
	db $24, $90, $31, $27
	db $2c, $70, $33, $07
	db $2c, $78, $34, $07
	db $2c, $7c, $38, $27
	db $2c, $84, $37, $27
	db $2c, $88, $34, $27
	db $2c, $90, $33, $27
	db $34, $70, $35, $07
	db $34, $78, $36, $07
	db $34, $7c, $3e, $27
	db $34, $84, $3d, $27
	db $34, $88, $36, $27
	db $34, $90, $35, $27
	db $3c, $74, $31, $47
	db $3c, $7c, $33, $47
	db $3c, $84, $33, $67
	db $3c, $8c, $31, $67
Gen2Frame_25:
	db 16
	db $64, $34, $31, $67
	db $64, $2c, $33, $67
	db $64, $24, $33, $47
	db $64, $1c, $31, $47
Gen2Frame_26:
	db 64
	db $64, $34, $31, $67
	db $64, $2c, $33, $67
	db $64, $24, $33, $47
	db $64, $1c, $31, $47
	db $54, $3c, $3a, $07
	db $54, $34, $39, $07
	db $54, $2c, $37, $27
	db $54, $24, $38, $27
	db $54, $1c, $39, $27
	db $54, $14, $3a, $27
	db $5c, $3c, $32, $07
	db $5c, $34, $31, $07
	db $5c, $2c, $3d, $27
	db $5c, $24, $3e, $27
	db $5c, $1c, $31, $27
	db $5c, $14, $32, $27
Gen2Frame_27:
	db 104
	db $64, $34, $31, $67
	db $64, $2c, $33, $67
	db $64, $24, $33, $47
	db $64, $1c, $31, $47
	db $54, $3c, $3a, $07
	db $54, $34, $39, $07
	db $54, $2c, $37, $27
	db $54, $24, $38, $27
	db $54, $1c, $39, $27
	db $54, $14, $3a, $27
	db $5c, $3c, $32, $07
	db $5c, $34, $31, $07
	db $5c, $2c, $3d, $27
	db $5c, $24, $3e, $27
	db $5c, $1c, $31, $27
	db $5c, $14, $32, $27
	db $44, $34, $31, $27
	db $44, $2c, $33, $27
	db $44, $24, $33, $07
	db $44, $1c, $31, $07
	db $4c, $3c, $34, $07
	db $4c, $34, $33, $07
	db $4c, $2c, $35, $27
	db $4c, $24, $36, $27
	db $4c, $1c, $33, $27
	db $4c, $14, $34, $27
Gen2Frame_28:
	db 104
	db $44, $34, $31, $27
	db $44, $2c, $33, $27
	db $44, $24, $33, $07
	db $44, $1c, $31, $07
	db $4c, $38, $31, $27
	db $4c, $30, $32, $27
	db $4c, $2c, $36, $07
	db $4c, $24, $35, $07
	db $4c, $20, $32, $07
	db $4c, $18, $31, $07
	db $54, $38, $33, $27
	db $54, $30, $34, $27
	db $54, $2c, $38, $07
	db $54, $24, $37, $07
	db $54, $20, $34, $07
	db $54, $18, $33, $07
	db $5c, $38, $35, $27
	db $5c, $30, $36, $27
	db $5c, $2c, $3e, $07
	db $5c, $24, $3d, $07
	db $5c, $20, $36, $07
	db $5c, $18, $35, $07
	db $64, $34, $31, $67
	db $64, $2c, $33, $67
	db $64, $24, $33, $47
	db $64, $1c, $31, $47
Gen2Frame_29:
	db 8
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
Gen2Frame_30:
	db 24
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
Gen2Frame_31:
	db 40
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
Gen2Frame_32:
	db 56
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
Gen2Frame_33:
	db 64
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
Gen2Frame_34:
	db 80
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
Gen2Frame_35:
	db 96
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
	db $20, $94, $31, $27
	db $20, $8c, $32, $27
	db $28, $94, $33, $27
	db $28, $8c, $34, $27
Gen2Frame_36:
	db 112
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
	db $20, $94, $31, $27
	db $20, $8c, $32, $27
	db $28, $94, $33, $27
	db $28, $8c, $34, $27
	db $30, $8c, $33, $27
	db $30, $84, $34, $27
	db $38, $8c, $3b, $27
	db $38, $84, $3c, $27
Gen2Frame_37:
	db 120
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
	db $20, $94, $31, $27
	db $20, $8c, $32, $27
	db $28, $94, $33, $27
	db $28, $8c, $34, $27
	db $30, $8c, $33, $27
	db $30, $84, $34, $27
	db $38, $8c, $3b, $27
	db $38, $84, $3c, $27
	db $08, $7c, $31, $07
	db $08, $84, $32, $07
Gen2Frame_38:
	db 136
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
	db $20, $94, $31, $27
	db $20, $8c, $32, $27
	db $28, $94, $33, $27
	db $28, $8c, $34, $27
	db $30, $8c, $33, $27
	db $30, $84, $34, $27
	db $38, $8c, $3b, $27
	db $38, $84, $3c, $27
	db $08, $7c, $31, $07
	db $08, $84, $32, $07
	db $10, $7c, $33, $07
	db $10, $84, $34, $07
	db $18, $7c, $35, $07
	db $18, $84, $36, $07
Gen2Frame_39:
	db 152
	db $08, $6c, $3d, $07
	db $08, $74, $3e, $07
	db $10, $6c, $39, $07
	db $10, $74, $3a, $07
	db $18, $6c, $35, $07
	db $18, $74, $36, $07
	db $20, $6c, $31, $07
	db $20, $74, $32, $07
	db $28, $6c, $33, $07
	db $28, $74, $34, $07
	db $30, $74, $33, $07
	db $30, $7c, $34, $07
	db $38, $74, $3b, $07
	db $38, $7c, $3c, $07
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
	db $20, $94, $31, $27
	db $20, $8c, $32, $27
	db $28, $94, $33, $27
	db $28, $8c, $34, $27
	db $30, $8c, $33, $27
	db $30, $84, $34, $27
	db $38, $8c, $3b, $27
	db $38, $84, $3c, $27
	db $08, $7c, $31, $07
	db $08, $84, $32, $07
	db $10, $7c, $33, $07
	db $10, $84, $34, $07
	db $18, $7c, $35, $07
	db $18, $84, $36, $07
	db $20, $7c, $37, $07
	db $20, $84, $38, $07
	db $28, $7c, $39, $07
	db $28, $84, $3a, $07
Gen2Frame_40:
	db 112
	db $08, $94, $3d, $27
	db $08, $8c, $3e, $27
	db $10, $94, $39, $27
	db $10, $8c, $3a, $27
	db $18, $94, $35, $27
	db $18, $8c, $36, $27
	db $20, $94, $31, $27
	db $20, $8c, $32, $27
	db $28, $94, $33, $27
	db $28, $8c, $34, $27
	db $30, $8c, $33, $27
	db $30, $84, $34, $27
	db $38, $8c, $3b, $27
	db $38, $84, $3c, $27
	db $08, $7c, $31, $07
	db $08, $84, $32, $07
	db $10, $7c, $33, $07
	db $10, $84, $34, $07
	db $18, $7c, $35, $07
	db $18, $84, $36, $07
	db $20, $7c, $37, $07
	db $20, $84, $38, $07
	db $28, $7c, $39, $07
	db $28, $84, $3a, $07
	db $30, $7c, $3b, $07
	db $30, $84, $3c, $07
	db $38, $7c, $3d, $07
	db $38, $84, $3e, $07
Gen2Frame_41:
	db 56
	db $08, $7c, $31, $07
	db $08, $84, $32, $07
	db $10, $7c, $33, $07
	db $10, $84, $34, $07
	db $18, $7c, $35, $07
	db $18, $84, $36, $07
	db $20, $7c, $37, $07
	db $20, $84, $38, $07
	db $28, $7c, $39, $07
	db $28, $84, $3a, $07
	db $30, $7c, $3b, $07
	db $30, $84, $3c, $07
	db $38, $7c, $3d, $07
	db $38, $84, $3e, $07
Gen2Frame_42:
	db 8
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
Gen2Frame_43:
	db 24
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
Gen2Frame_44:
	db 40
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
Gen2Frame_45:
	db 56
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
Gen2Frame_46:
	db 64
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
Gen2Frame_47:
	db 80
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
Gen2Frame_48:
	db 96
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
	db $50, $14, $31, $07
	db $50, $1c, $32, $07
	db $58, $14, $33, $07
	db $58, $1c, $34, $07
Gen2Frame_49:
	db 112
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
	db $50, $14, $31, $07
	db $50, $1c, $32, $07
	db $58, $14, $33, $07
	db $58, $1c, $34, $07
	db $60, $1c, $33, $07
	db $60, $24, $34, $07
	db $68, $1c, $3b, $07
	db $68, $24, $3c, $07
Gen2Frame_50:
	db 120
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
	db $50, $14, $31, $07
	db $50, $1c, $32, $07
	db $58, $14, $33, $07
	db $58, $1c, $34, $07
	db $60, $1c, $33, $07
	db $60, $24, $34, $07
	db $68, $1c, $3b, $07
	db $68, $24, $3c, $07
	db $38, $2c, $31, $27
	db $38, $24, $32, $27
Gen2Frame_51:
	db 136
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
	db $50, $14, $31, $07
	db $50, $1c, $32, $07
	db $58, $14, $33, $07
	db $58, $1c, $34, $07
	db $60, $1c, $33, $07
	db $60, $24, $34, $07
	db $68, $1c, $3b, $07
	db $68, $24, $3c, $07
	db $38, $2c, $31, $27
	db $38, $24, $32, $27
	db $40, $2c, $33, $27
	db $40, $24, $34, $27
	db $48, $2c, $35, $27
	db $48, $24, $36, $27
Gen2Frame_52:
	db 152
	db $38, $3c, $3d, $27
	db $38, $34, $3e, $27
	db $40, $3c, $39, $27
	db $40, $34, $3a, $27
	db $48, $3c, $35, $27
	db $48, $34, $36, $27
	db $50, $3c, $31, $27
	db $50, $34, $32, $27
	db $58, $3c, $33, $27
	db $58, $34, $34, $27
	db $60, $34, $33, $27
	db $60, $2c, $34, $27
	db $68, $34, $3b, $27
	db $68, $2c, $3c, $27
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
	db $50, $14, $31, $07
	db $50, $1c, $32, $07
	db $58, $14, $33, $07
	db $58, $1c, $34, $07
	db $60, $1c, $33, $07
	db $60, $24, $34, $07
	db $68, $1c, $3b, $07
	db $68, $24, $3c, $07
	db $38, $2c, $31, $27
	db $38, $24, $32, $27
	db $40, $2c, $33, $27
	db $40, $24, $34, $27
	db $48, $2c, $35, $27
	db $48, $24, $36, $27
	db $50, $2c, $37, $27
	db $50, $24, $38, $27
	db $58, $2c, $39, $27
	db $58, $24, $3a, $27
Gen2Frame_53:
	db 112
	db $38, $14, $3d, $07
	db $38, $1c, $3e, $07
	db $40, $14, $39, $07
	db $40, $1c, $3a, $07
	db $48, $14, $35, $07
	db $48, $1c, $36, $07
	db $50, $14, $31, $07
	db $50, $1c, $32, $07
	db $58, $14, $33, $07
	db $58, $1c, $34, $07
	db $60, $1c, $33, $07
	db $60, $24, $34, $07
	db $68, $1c, $3b, $07
	db $68, $24, $3c, $07
	db $38, $2c, $31, $27
	db $38, $24, $32, $27
	db $40, $2c, $33, $27
	db $40, $24, $34, $27
	db $48, $2c, $35, $27
	db $48, $24, $36, $27
	db $50, $2c, $37, $27
	db $50, $24, $38, $27
	db $58, $2c, $39, $27
	db $58, $24, $3a, $27
	db $60, $2c, $3b, $27
	db $60, $24, $3c, $27
	db $68, $2c, $3d, $27
	db $68, $24, $3e, $27
Gen2Frame_54:
	db 56
	db $38, $2c, $31, $27
	db $38, $24, $32, $27
	db $40, $2c, $33, $27
	db $40, $24, $34, $27
	db $48, $2c, $35, $27
	db $48, $24, $36, $27
	db $50, $2c, $37, $27
	db $50, $24, $38, $27
	db $58, $2c, $39, $27
	db $58, $24, $3a, $27
	db $60, $2c, $3b, $27
	db $60, $24, $3c, $27
	db $68, $2c, $3d, $27
	db $68, $24, $3e, $27
Gen2Frame_55:
	db 60
	db $24, $88, $32, $06
	db $24, $80, $33, $06
	db $24, $88, $33, $26
	db $2c, $80, $33, $46
	db $2c, $88, $33, $66
	db $20, $84, $32, $06
	db $20, $7c, $33, $06
	db $20, $84, $33, $26
	db $28, $7c, $33, $46
	db $28, $84, $33, $66
	db $1c, $80, $32, $06
	db $1c, $78, $33, $06
	db $1c, $80, $33, $26
	db $24, $78, $33, $46
	db $24, $80, $33, $66
Gen2Frame_56:
	db 72
	db $24, $88, $32, $06
	db $2a, $82, $32, $06
	db $2a, $7a, $33, $06
	db $2a, $82, $33, $26
	db $32, $7a, $33, $46
	db $32, $82, $33, $66
	db $20, $84, $32, $06
	db $26, $7e, $32, $06
	db $26, $76, $33, $06
	db $26, $7e, $33, $26
	db $2e, $76, $33, $46
	db $2e, $7e, $33, $66
	db $1c, $80, $32, $06
	db $22, $7a, $32, $06
	db $22, $72, $33, $06
	db $22, $7a, $33, $26
	db $2a, $72, $33, $46
	db $2a, $7a, $33, $66
Gen2Frame_57:
	db 84
	db $24, $88, $32, $06
	db $2a, $82, $32, $06
	db $30, $7c, $32, $06
	db $30, $74, $33, $06
	db $30, $7c, $33, $26
	db $38, $74, $33, $46
	db $38, $7c, $33, $66
	db $20, $84, $32, $06
	db $26, $7e, $32, $06
	db $2c, $78, $32, $06
	db $2c, $70, $33, $06
	db $2c, $78, $33, $26
	db $34, $70, $33, $46
	db $34, $78, $33, $66
	db $1c, $80, $32, $06
	db $22, $7a, $32, $06
	db $28, $74, $32, $06
	db $28, $6c, $33, $06
	db $28, $74, $33, $26
	db $30, $6c, $33, $46
	db $30, $74, $33, $66
Gen2Frame_58:
	db 36
	db $24, $88, $32, $06
	db $2a, $82, $32, $06
	db $30, $7c, $32, $06
	db $20, $84, $32, $06
	db $26, $7e, $32, $06
	db $2c, $78, $32, $06
	db $1c, $80, $32, $06
	db $22, $7a, $32, $06
	db $28, $74, $32, $06
Gen2Frame_59:
	db 60
	db $4c, $20, $32, $26
	db $4c, $28, $33, $26
	db $4c, $20, $33, $06
	db $54, $28, $33, $66
	db $54, $20, $33, $46
	db $48, $24, $32, $26
	db $48, $2c, $33, $26
	db $48, $24, $33, $06
	db $50, $2c, $33, $66
	db $50, $24, $33, $46
	db $44, $28, $32, $26
	db $44, $30, $33, $26
	db $44, $28, $33, $06
	db $4c, $30, $33, $66
	db $4c, $28, $33, $46
Gen2Frame_60:
	db 72
	db $4c, $20, $32, $26
	db $52, $26, $32, $26
	db $52, $2e, $33, $26
	db $52, $26, $33, $06
	db $5a, $2e, $33, $66
	db $5a, $26, $33, $46
	db $48, $24, $32, $26
	db $4e, $2a, $32, $26
	db $4e, $32, $33, $26
	db $4e, $2a, $33, $06
	db $56, $32, $33, $66
	db $56, $2a, $33, $46
	db $44, $28, $32, $26
	db $4a, $2e, $32, $26
	db $4a, $36, $33, $26
	db $4a, $2e, $33, $06
	db $52, $36, $33, $66
	db $52, $2e, $33, $46
Gen2Frame_61:
	db 84
	db $4c, $20, $32, $26
	db $52, $26, $32, $26
	db $58, $2c, $32, $26
	db $58, $34, $33, $26
	db $58, $2c, $33, $06
	db $60, $34, $33, $66
	db $60, $2c, $33, $46
	db $48, $24, $32, $26
	db $4e, $2a, $32, $26
	db $54, $30, $32, $26
	db $54, $38, $33, $26
	db $54, $30, $33, $06
	db $5c, $38, $33, $66
	db $5c, $30, $33, $46
	db $44, $28, $32, $26
	db $4a, $2e, $32, $26
	db $50, $34, $32, $26
	db $50, $3c, $33, $26
	db $50, $34, $33, $06
	db $58, $3c, $33, $66
	db $58, $34, $33, $46
Gen2Frame_62:
	db 36
	db $4c, $20, $32, $26
	db $52, $26, $32, $26
	db $58, $2c, $32, $26
	db $48, $24, $32, $26
	db $4e, $2a, $32, $26
	db $54, $30, $32, $26
	db $44, $28, $32, $26
	db $4a, $2e, $32, $26
	db $50, $34, $32, $26
Gen2Frame_63:
	db 20
	db $1c, $90, $32, $06
	db $1c, $88, $33, $06
	db $1c, $90, $33, $26
	db $24, $88, $33, $46
	db $24, $90, $33, $66
Gen2Frame_64:
	db 24
	db $1c, $90, $32, $06
	db $22, $8a, $32, $06
	db $22, $82, $33, $06
	db $22, $8a, $33, $26
	db $2a, $82, $33, $46
	db $2a, $8a, $33, $66
Gen2Frame_65:
	db 28
	db $1c, $90, $32, $06
	db $22, $8a, $32, $06
	db $28, $84, $32, $06
	db $28, $7c, $33, $06
	db $28, $84, $33, $26
	db $30, $7c, $33, $46
	db $30, $84, $33, $66
Gen2Frame_66:
	db 32
	db $1c, $90, $32, $06
	db $22, $8a, $32, $06
	db $28, $84, $32, $06
	db $2e, $7e, $32, $06
	db $2e, $76, $33, $06
	db $2e, $7e, $33, $26
	db $36, $76, $33, $46
	db $36, $7e, $33, $66
Gen2Frame_67:
	db 36
	db $1c, $90, $32, $06
	db $22, $8a, $32, $06
	db $28, $84, $32, $06
	db $2e, $7e, $32, $06
	db $34, $78, $32, $06
	db $34, $70, $33, $06
	db $34, $78, $33, $26
	db $3c, $70, $33, $46
	db $3c, $78, $33, $66
Gen2Frame_68:
	db 40
	db $1c, $90, $32, $06
	db $22, $8a, $32, $06
	db $28, $84, $32, $06
	db $2e, $7e, $32, $06
	db $34, $78, $32, $06
	db $3a, $72, $32, $06
	db $3a, $6a, $33, $06
	db $3a, $72, $33, $26
	db $42, $6a, $33, $46
	db $42, $72, $33, $66
Gen2Frame_69:
	db 24
	db $1c, $90, $32, $06
	db $22, $8a, $32, $06
	db $28, $84, $32, $06
	db $2e, $7e, $32, $06
	db $34, $78, $32, $06
	db $3a, $72, $32, $06
Gen2Frame_70:
	db 20
	db $44, $18, $32, $26
	db $44, $20, $33, $26
	db $44, $18, $33, $06
	db $4c, $20, $33, $66
	db $4c, $18, $33, $46
Gen2Frame_71:
	db 24
	db $44, $18, $32, $26
	db $4a, $1e, $32, $26
	db $4a, $26, $33, $26
	db $4a, $1e, $33, $06
	db $52, $26, $33, $66
	db $52, $1e, $33, $46
Gen2Frame_72:
	db 28
	db $44, $18, $32, $26
	db $4a, $1e, $32, $26
	db $50, $24, $32, $26
	db $50, $2c, $33, $26
	db $50, $24, $33, $06
	db $58, $2c, $33, $66
	db $58, $24, $33, $46
Gen2Frame_73:
	db 32
	db $44, $18, $32, $26
	db $4a, $1e, $32, $26
	db $50, $24, $32, $26
	db $56, $2a, $32, $26
	db $56, $32, $33, $26
	db $56, $2a, $33, $06
	db $5e, $32, $33, $66
	db $5e, $2a, $33, $46
Gen2Frame_74:
	db 36
	db $44, $18, $32, $26
	db $4a, $1e, $32, $26
	db $50, $24, $32, $26
	db $56, $2a, $32, $26
	db $5c, $30, $32, $26
	db $5c, $38, $33, $26
	db $5c, $30, $33, $06
	db $64, $38, $33, $66
	db $64, $30, $33, $46
Gen2Frame_75:
	db 32
	db $44, $18, $32, $26
	db $4a, $1e, $32, $26
	db $50, $24, $32, $26
	db $56, $2a, $32, $26
	db $5c, $30, $32, $26
	db $62, $36, $32, $26
	db $62, $3e, $33, $26
	db $62, $36, $33, $06
Gen2Frame_76:
	db 24
	db $44, $18, $32, $26
	db $4a, $1e, $32, $26
	db $50, $24, $32, $26
	db $56, $2a, $32, $26
	db $5c, $30, $32, $26
	db $62, $36, $32, $26
Gen2Frame_77:
	db 64
	db $18, $74, $31, $06
	db $18, $7c, $32, $06
	db $20, $74, $33, $06
	db $20, $7c, $34, $06
	db $18, $84, $32, $26
	db $18, $8c, $31, $26
	db $20, $84, $34, $26
	db $20, $8c, $33, $26
	db $28, $74, $33, $46
	db $28, $7c, $34, $46
	db $30, $74, $31, $46
	db $30, $7c, $32, $46
	db $28, $84, $34, $66
	db $28, $8c, $33, $66
	db $30, $84, $32, $66
	db $30, $8c, $31, $66
Gen2Frame_78:
	db 64
	db $48, $1c, $31, $06
	db $48, $24, $32, $06
	db $50, $1c, $33, $06
	db $50, $24, $34, $06
	db $48, $2c, $32, $26
	db $48, $34, $31, $26
	db $50, $2c, $34, $26
	db $50, $34, $33, $26
	db $58, $1c, $33, $46
	db $58, $24, $34, $46
	db $60, $1c, $31, $46
	db $60, $24, $32, $46
	db $58, $2c, $34, $66
	db $58, $34, $33, $66
	db $60, $2c, $32, $66
	db $60, $34, $31, $66
Gen2Frame_79:
	db 112
	db $4c, $11, $39, $06
	db $54, $11, $39, $06
	db $5c, $11, $39, $06
	db $4c, $19, $39, $06
	db $54, $19, $39, $06
	db $5c, $19, $39, $06
	db $44, $19, $39, $06
	db $64, $19, $39, $06
	db $4c, $21, $39, $06
	db $54, $21, $39, $06
	db $5c, $21, $39, $06
	db $44, $21, $39, $06
	db $64, $21, $39, $06
	db $3c, $21, $39, $06
	db $4c, $27, $39, $06
	db $54, $27, $39, $06
	db $5c, $27, $39, $06
	db $44, $27, $39, $06
	db $64, $27, $39, $06
	db $3c, $27, $39, $06
	db $4c, $2f, $39, $06
	db $54, $2f, $39, $06
	db $5c, $2f, $39, $06
	db $44, $2f, $39, $06
	db $64, $2f, $39, $06
	db $4c, $37, $39, $06
	db $54, $37, $39, $06
	db $5c, $37, $39, $06
Gen2Frame_80:
	db 64
	db $4c, $1a, $39, $06
	db $54, $1a, $39, $06
	db $5c, $1a, $39, $06
	db $4c, $22, $39, $06
	db $54, $22, $39, $06
	db $5c, $22, $39, $06
	db $44, $22, $39, $06
	db $64, $22, $39, $06
	db $4c, $26, $39, $06
	db $54, $26, $39, $06
	db $5c, $26, $39, $06
	db $44, $26, $39, $06
	db $64, $26, $39, $06
	db $4c, $2e, $39, $06
	db $54, $2e, $39, $06
	db $5c, $2e, $39, $06
Gen2Frame_81:
	db 24
	db $4c, $23, $39, $06
	db $54, $23, $39, $06
	db $5c, $23, $39, $06
	db $4c, $25, $39, $06
	db $54, $25, $39, $06
	db $5c, $25, $39, $06
Gen2Frame_82:
	db 36
	db $24, $78, $3e, $06
	db $24, $80, $3f, $06
	db $24, $88, $3e, $26
	db $2c, $78, $40, $06
	db $2c, $80, $41, $06
	db $2c, $88, $40, $66
	db $34, $78, $3e, $46
	db $34, $80, $3f, $66
	db $34, $88, $3e, $66
Gen2Frame_83:
	db 120
	db $24, $97, $39, $06
	db $2c, $97, $39, $06
	db $34, $97, $39, $06
	db $24, $8f, $39, $06
	db $2c, $8f, $39, $06
	db $34, $8f, $39, $06
	db $1c, $8f, $39, $06
	db $3c, $8f, $39, $06
	db $24, $87, $39, $06
	db $2c, $87, $39, $06
	db $34, $87, $39, $06
	db $1c, $87, $39, $06
	db $3c, $87, $39, $06
	db $14, $87, $39, $06
	db $44, $87, $39, $06
	db $24, $81, $39, $06
	db $2c, $81, $39, $06
	db $34, $81, $39, $06
	db $1c, $81, $39, $06
	db $3c, $81, $39, $06
	db $14, $81, $39, $06
	db $44, $81, $39, $06
	db $24, $79, $39, $06
	db $2c, $79, $39, $06
	db $34, $79, $39, $06
	db $1c, $79, $39, $06
	db $3c, $79, $39, $06
	db $24, $71, $39, $06
	db $2c, $71, $39, $06
	db $34, $71, $39, $06
Gen2Frame_84:
	db 64
	db $24, $8e, $39, $06
	db $2c, $8e, $39, $06
	db $34, $8e, $39, $06
	db $24, $86, $39, $06
	db $2c, $86, $39, $06
	db $34, $86, $39, $06
	db $1c, $86, $39, $06
	db $3c, $86, $39, $06
	db $24, $82, $39, $06
	db $2c, $82, $39, $06
	db $34, $82, $39, $06
	db $1c, $82, $39, $06
	db $3c, $82, $39, $06
	db $24, $7a, $39, $06
	db $2c, $7a, $39, $06
	db $34, $7a, $39, $06
Gen2Frame_85:
	db 24
	db $24, $85, $39, $06
	db $2c, $85, $39, $06
	db $34, $85, $39, $06
	db $24, $83, $39, $06
	db $2c, $83, $39, $06
	db $34, $83, $39, $06
Gen2Frame_86:
	db 36
	db $54, $20, $3e, $06
	db $54, $28, $3f, $06
	db $54, $30, $3e, $26
	db $5c, $20, $40, $06
	db $5c, $28, $41, $06
	db $5c, $30, $40, $66
	db $64, $20, $3e, $46
	db $64, $28, $3f, $66
	db $64, $30, $3e, $66

SECTION "Gen 2 effect artwork", ROMX, BANK[$47]
Gen2GFX_THUNDERSHOCK:
	INCBIN "gfx/battle/gen2/lightning.2bpp"
	INCBIN "gfx/battle/gen2/explosion.2bpp"
Gen2GFX_THUNDERBOLT:
	INCBIN "gfx/battle/gen2/lightning.2bpp"
	INCBIN "gfx/battle/gen2/explosion.2bpp"
Gen2GFX_THUNDER_WAVE:
	INCBIN "gfx/battle/gen2/lightning.2bpp"
Gen2GFX_THUNDER:
	INCBIN "gfx/battle/gen2/lightning.2bpp"
Gen2GFX_SCRATCH:
	INCBIN "gfx/battle/gen2/cut.2bpp"
Gen2GFX_CUT:
	INCBIN "gfx/battle/gen2/cut.2bpp"
Gen2GFX_TACKLE:
	INCBIN "gfx/battle/gen2/hit.2bpp"
Gen2GFX_QUICK_ATTACK:
	INCBIN "gfx/battle/gen2/speed.2bpp"
	INCBIN "gfx/battle/gen2/hit.2bpp"
