; Generated by scripts/build_terrain.py; do not edit.
ColorFlowerTile1::
	db $00,$81,$18,$18,$3c,$24,$7e,$db,$7e,$42,$38,$a5,$00,$7e,$00,$99
	assert (@ - ColorFlowerTile1) == 16

ColorFlowerTile2::
	db $00,$81,$0c,$0c,$1e,$12,$3f,$ad,$0f,$e1,$1c,$73,$00,$3e,$00,$99
	assert (@ - ColorFlowerTile2) == 16

ColorFlowerTile3::
	db $18,$99,$3c,$24,$7e,$5a,$7e,$c3,$38,$24,$00,$db,$00,$7e,$00,$99
	assert (@ - ColorFlowerTile3) == 16

	assert ColorFlowerTile3 - ColorFlowerTile1 == 2 * TILE_SIZE
