; 8 bytes per tileset for 8 palettes, which are taken from MapPalettes.
MapPaletteSets:
	table_width 2, MapPaletteSets
	dw OverworldPalSet   ; OVERWORLD
	dw RedsHouse1PalSet  ; REDS_HOUSE_1
	dw MartPalSet        ; MART
	dw ForestPalSet      ; FOREST
	dw RedsHouse2PalSet  ; REDS_HOUSE_2
	dw DojoPalSet        ; DOJO
	dw PokecenterPalSet  ; POKECENTER
	dw GymPalSet         ; GYM
	dw HousePalSet       ; HOUSE
	dw ForestGatePalSet  ; FOREST_GATE
	dw MuseumPalSet      ; MUSEUM
	dw UndergroundPalSet ; UNDERGROUND
	dw GatePalSet        ; GATE
	dw ShipPalSet        ; SHIP
	dw ShipPortPalSet    ; SHIP_PORT
	dw CemeteryPalSet    ; CEMETERY
	dw InteriorPalSet    ; INTERIOR
	dw CavernPalSet      ; CAVERN
	dw LobbyPalSet       ; LOBBY
	dw MansionPalSet     ; MANSION
	dw LabPalSet         ; LAB
	dw ClubPalSet        ; CLUB
	dw FacilityPalSet    ; FACILITY
	dw PlateauPalSet     ; PLATEAU
	dw HousePalSet       ; BEACH_HOUSE
	assert_table_length NUM_TILESETS


OverworldPalSet:
PlateauPalSet:
	db OUTDOOR_MASONRY, OUTDOOR_RED, OUTDOOR_GREEN, OUTDOOR_BLUE, OUTDOOR_GLASS, OUTDOOR_BROWN, OUTDOOR_ROOF, CRYS_TEXTBOX

ForestPalSet:
	db OUTDOOR_MASONRY, FOREST_ROCKS, OUTDOOR_GREEN, OUTDOOR_BLUE, OUTDOOR_GLASS, OUTDOOR_BROWN, FOREST_TREES, CRYS_TEXTBOX

RedsHouse1PalSet:
RedsHouse2PalSet:
DojoPalSet:
HousePalSet:
ShipPalSet:
ClubPalSet:
	db INDOOR_WOOD, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, CRYS_TEXTBOX

GymPalSet:
FacilityPalSet:
	db INDOOR_TEAL, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, CRYS_TEXTBOX

ForestGatePalSet:
	db INDOOR_SANDSTONE, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, CRYS_TEXTBOX

UndergroundPalSet:
ShipPortPalSet:
	db INDOOR_STONE, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, CRYS_TEXTBOX

MartPalSet:
LabPalSet:
	db INDOOR_TEAL, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, PC_POKEBALL_PAL

InteriorPalSet:
LobbyPalSet:
	db INDOOR_SANDSTONE, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, PC_POKEBALL_PAL

MansionPalSet:
	db INDOOR_LAVENDER, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, PC_POKEBALL_PAL

PokecenterPalSet:
	db INDOOR_TEAL, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, BENCH_GUY_PAL, INDOOR_BROWN, INDOOR_STEEL, PC_POKEBALL_PAL

MuseumPalSet:
GatePalSet:
	db INDOOR_SANDSTONE, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_STEEL, ALT_TEXTBOX_PAL

CemeteryPalSet:
	db INDOOR_LAVENDER, INDOOR_RED, INDOOR_GREEN, INDOOR_BLUE, INDOOR_YELLOW, INDOOR_BROWN, INDOOR_PURPLE, CRYS_TEXTBOX

CavernPalSet:
	db CAVE_GRAY, CAVE_RED, CAVE_GREEN, CAVE_BLUE, CAVE_YELLOW, CAVE_BROWN, CAVE_LIGHT_BLUE, CRYS_TEXTBOX
