#!/usr/bin/env python3
"""Generate CGB-only trainer materials from the existing Gen 2 back pictures.

White eyes, hair, shirt sleeves and coat panels remain white. Small material
masks separate exposed skin from the white background; outlines are unchanged.
The native compressed pictures remain available to DMG/SGB.
"""
import argparse
from collections import deque
from pathlib import Path
from PIL import Image
from build_portraits import encode

ROOT = Path(__file__).resolve().parents[1]
PICTURES = {'Red': 'player/redb', 'Oak': 'battle/prof.oakb', 'OldMan': 'battle/oldmanb'}


def colorize(name):
    image = Image.open(ROOT / f'src/gfx/{PICTURES[name]}.png').convert('L')
    grid = [[3-image.getpixel((x,y))//85 for x in range(48)] for y in range(48)]
    # Mark exterior white so material fills cannot expand the silhouette.
    outside, queue = set(), deque()
    for y in range(48):
        for x in range(48):
            if (x in [0,47] or y in [0,47]) and grid[y][x] == 0:
                outside.add((x,y)); queue.append((x,y))
    while queue:
        x,y = queue.popleft()
        for xx,yy in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
            if 0<=xx<48 and 0<=yy<48 and grid[yy][xx]==0 and (xx,yy) not in outside:
                outside.add((xx,yy)); queue.append((xx,yy))
    result = [row[:] for row in grid]
    for y in range(48):
        for x in range(48):
            old = grid[y][x]
            if name == 'Red':
                skin = (22<=x<=33 and 21<=y<=28) or (29<=x<=46 and 40<=y<=47)
            elif name == 'Oak':
                skin = (30<=x<=39 and 11<=y<=25) or (25<=x<=33 and 23<=y<=28)
                if old==1 and not skin:
                    result[y][x] = 2  # Silver hair and white coat shading.
            else:
                skin = 25<=x<=37 and 11<=y<=27
                if old==1 and not skin:
                    result[y][x] = 2  # Hair and coat shading stay cool gray.
            if old==0 and skin and (x,y) not in outside:
                result[y][x] = 1
            assert old!=3 or result[y][x]==3
            assert (x,y) not in outside or result[y][x]==0
    # Match LoadBackSpriteUnzoomed's original 6x6 -> 7x7 alignment.
    padded = [[0]*56 for _ in range(56)]
    for y in range(48): padded[y+8][8:56] = result[y]
    return padded


def generate():
    result = '; Generated by scripts/build_battle_colors.py; do not edit.\n'
    for name in PICTURES:
        data = encode(colorize(name), True)
        result += f'\nColor{name}BackTiles::\n'
        result += ''.join('\tdb '+','.join(f'${v:02x}' for v in data[i:i+16])+'\n'
                          for i in range(0,len(data),16))
        result += f'\tassert (@ - Color{name}BackTiles) == PIC_SIZE tiles\n'
    return result


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    output=ROOT/'src/color/battle_trainer_data.asm'
    if args.check: assert output.read_text()==generate(), 'Regenerate battle trainer materials'
    else: output.write_text(generate())
    print('CGB trainer material data verified' if args.check else f'Wrote {output}')
