#!/usr/bin/env python3
"""Separate skin from white uniforms in CGB-only copies of the original tiles.

The original monochrome art shares shade 1 between skin, coats, hats and hair.
These small, frame-specific material masks retain the silhouettes and outlines.
Generated assembly is checked in; normal builds do not require Pillow.
"""
import argparse
from pathlib import Path

from build_portraits import encode
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SPRITES = {'scientist': 'Scientist', 'oak': 'Oak', 'cook': 'Cook', 'seel': 'Seel'}


def colorize(name):
    source = Image.open(ROOT / f'src/gfx/sprites/{name}.png').convert('L')
    grid = [[3 - source.getpixel((x, y)) // 85 for x in range(16)]
            for y in range(source.height)]
    colored = [row[:] for row in grid]
    for yy, row in enumerate(grid):
        frame, y = divmod(yy, 16)
        walking = frame >= 3
        facing = frame % 3  # down, up, left (right uses hardware mirroring)
        for x, pixel in enumerate(row):
            if name == 'seel':
                # Seel's body is white; shade 2 is its original dark contour.
                colored[yy][x] = {1: 2, 2: 3}.get(pixel, pixel)
                continue
            if pixel not in (1, 2):
                continue
            # Keep ears, face, and hands warm. White replaces shared light
            # pixels only within the coat, chef's hat, or Oak's silver hair.
            coat = y >= 10 + walking
            if facing in (0, 1):
                hands = (x <= 3 or x >= 12) and y <= 11 + walking
            else:
                hands = x == (8 if walking else 6) and y in (11 + walking, 12 + walking)
            white = coat and not hands
            if name == 'cook':
                white |= y <= 4 + walking or (facing == 1 and y == 5 + walking and 5 <= x <= 10)
            if name == 'oak':
                if facing == 0:
                    white |= y <= 3 + walking
                elif facing == 1:
                    white |= y <= 4 + walking or (y <= 8 + walking and 4 <= x <= 11)
                else:
                    white |= y <= 3 + walking or (y <= 7 + walking and x >= 9)
            colored[yy][x] = 2 if white else 1
    # No transparency or outline changes for people, even across walk frames.
    if name != 'seel':
        assert all((a in (0, 3)) == (b in (0, 3)) and (a == b if a in (0, 3) else True)
                   for ra, rb in zip(grid, colored) for a, b in zip(ra, rb))
    return colored


def generate():
    text = '; Generated by scripts/build_overworld_sprites.py; do not edit.\n'
    text += 'SECTION "CGB white clothing sprites", ROMX, BANK[$45]\n\n'
    for name, label in SPRITES.items():
        data = encode(colorize(name), False)
        text += f'Color{label}Sprite::\n'
        text += ''.join('\tdb ' + ','.join(f'${b:02x}' for b in data[i:i+16]) + '\n'
                        for i in range(0, len(data), 16))
        text += f'\tassert (@ - Color{label}Sprite) == {len(data)}\n\n'
    return text


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'src/color/overworld_sprites.asm'
    generated = generate()
    if args.check:
        assert output.read_text() == generated, 'Regenerate CGB overworld sprite data'
    else:
        output.write_text(generated)
    print('CGB uniforms, hair, and Seel tiles verified' if args.check else f'Wrote {output}')
