#!/usr/bin/env python3
"""Separate outdoor materials in CGB-only tiles; preserve original DMG artwork.

Barrier masks are derived from complete objects, not individual 8x8 tiles:
enclosed white belongs to the wood/stone, edge-connected white to the ground.
Flower material masks retain the three poses while separating petals/leaves.
Generated assembly is checked in; normal builds need no image-processing tools.
"""
import argparse
from pathlib import Path
from PIL import Image
from build_portraits import encode

ROOT = Path(__file__).resolve().parents[1]
FLOWERS = [
    ['20000002', '00033000', '00311300', '23133132',
     '03111130', '20311202', '02222220', '20022002'],
    ['20000002', '00003300', '00031130', '20313313',
     '22201113', '02231122', '00222220', '20022002'],
    ['20033002', '00311300', '03133130', '23111132',
     '00311200', '22022022', '02222220', '20022002'],
]
FLOWERS = [[[int(v) for v in row] for row in frame] for frame in FLOWERS]
OBJECTS = {
    'overworld': {'wooden_post': [[0x0e], [0x55]],
                  'round_boulder': [[0x2a, 0x2b], [0x3a, 0x3b]]},
    'forest': {'small_stone': [[0x37]],
               'cut_stump': [[0x02, 0x03], [0x12, 0x13]]},
}


def load(name):
    im = Image.open(ROOT / f'src/gfx/tilesets/{name}.png').convert('L')
    return [[3-im.getpixel((x, y))//85 for x in range(im.width)] for y in range(im.height)]


def object_grid(grid, tiles):
    return [[grid[t//16*8+y][t%16*8+x] for t in row for x in range(8)]
            for row in tiles for y in range(8)]


def colorize(name):
    original = load(name)
    grid = [row[:] for row in original]
    for material, tiles in OBJECTS[name].items():
        obj = object_grid(original, tiles)
        width, height = len(obj[0]), len(obj)
        outside, pending = set(), []
        for y in range(height):
            for x in range(width):
                if (x in (0, width-1) or y in (0, height-1)) and obj[y][x] == 0:
                    outside.add((x, y)); pending.append((x, y))
        while pending:
            x, y = pending.pop()
            for a, b in [(x-1, y), (x+1, y), (x, y-1), (x, y+1)]:
                if 0 <= a < width and 0 <= b < height and obj[b][a] == 0 and (a, b) not in outside:
                    outside.add((a, b)); pending.append((a, b))
        for y in range(height):
            for x in range(width):
                if material == 'cut_stump' and not (4 <= x <= 11 and 4 <= y <= 12):
                    # Do not recolor the dithered ground around the stump.
                    continue
                if obj[y][x] != 0 or (x, y) in outside:
                    continue
                t = tiles[y//8][x//8]
                shade = 2 if x >= width*2//3 else 1
                if material == 'cut_stump':
                    shade = 1 if y < 8 else 2
                grid[t//16*8+y%8][t%16*8+x%8] = shade
        if material == 'cut_stump':
            # Preserve the end-grain ring against the newly colored cut face.
            for y in range(4, 8):
                for x in range(5, 11):
                    if obj[y][x] == 1:
                        t = tiles[y//8][x//8]
                        grid[t//16*8+y%8][t%16*8+x%8] = 2
    if name == 'overworld':
        for y in range(8):
            grid[y][3*8:4*8] = FLOWERS[0][y]
    return grid


def emit(label, raw):
    return label + '::\n' + ''.join(
        '\tdb ' + ','.join(f'${v:02x}' for v in raw[i:i+16]) + '\n'
        for i in range(0, len(raw), 16)) + f'\tassert (@ - {label}) == {len(raw)}\n\n'


def generate():
    heading = '; Generated by scripts/build_terrain.py; do not edit.\n'
    tiles = heading
    for name in OBJECTS:
        raw = encode(colorize(name), False)
        assert len(raw) == 0x600
        tiles += emit('ColorTerrain' + name.title(), raw)
    # Flower animation runs in VBlank. Keep its tiny frames in ROM0 to avoid
    # adding a ROM bank switch to the display interrupt.
    flowers = heading + ''.join(emit(f'ColorFlowerTile{i}', encode(frame, False))
                                for i, frame in enumerate(FLOWERS, 1))
    flowers += '\tassert ColorFlowerTile3 - ColorFlowerTile1 == 2 * TILE_SIZE\n'
    return {'src/color/terrain_data.asm': tiles, 'src/color/flower_data.asm': flowers}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, source in generate().items():
        path = ROOT / name
        if args.check:
            assert path.read_text() == source, f'Regenerate {name}'
        else:
            path.write_text(source)
    print('CGB barrier/stone tiles and all three flower poses verified' if args.check else 'Generated CGB outdoor materials')
