#!/usr/bin/env python3
"""Generate CGB portrait tile data from Yellow's original indexed artwork.

Original PNGs and monochrome/SGB graphics stay unchanged. Fur masks distinguish
enclosed white regions from the white field and small eye highlights. Partial
animation patches are classified in their complete 40x40 frame, not in isolation.
The generated assembly is checked in, so ordinary ROM builds need no Pillow.
"""
import argparse
from pathlib import Path
import re

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
PARTS = {
    'e40cc': ('e4000', 0, 16), 'e41d2': ('e411c', 0, 24),
    'e4323': ('e4272', 0, 0), 'e444b': ('e4383', 0, 8),
    'e463b': ('e458b', 24, 8), 'e472e': ('e467b', 0, 16),
    'e4a99': ('e49d1', 0, 16), 'e4bde': ('e4b39', 0, 16),
}
POT_FRAMES = {'e67d6', 'e682f', 'e69bf', 'e6b4f'}
SHOCK_FRAMES = {'e5794', 'e79f3'}
PALETTE = [(255, 255, 255), (255, 230, 24), (222, 66, 24), (24, 24, 24)]


def load(name):
    with Image.open(ROOT / f'src/gfx/pikachu/unknown_{name}.png') as source:
        source = source.convert('L')
        return [[3 - source.getpixel((x, y)) // 85 for x in range(source.width)]
                for y in range(source.height)]


def neighbors(x, y):
    return [(a, b) for a, b in [(x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)]
            if 0 <= a < 40 and 0 <= b < 40]


def colorize(name):
    part = load(name)
    width, height = len(part[0]), len(part)
    x0, y0 = 0, 0
    if name in PARTS:
        base, x0, y0 = PARTS[name]
        grid = load(base)
        for y, row in enumerate(part):
            grid[y + y0][x0:x0 + width] = row
    else:
        grid = part
    assert len(grid) == 40 and len(grid[0]) == 40
    colored = [row[:] for row in grid]
    seen = set()
    for y in range(40):
        for x in range(40):
            if grid[y][x] != 0 or (x, y) in seen:
                continue
            pending, region = [(x, y)], []
            seen.add((x, y))
            while pending:
                xx, yy = pending.pop()
                region.append((xx, yy))
                for a, b in neighbors(xx, yy):
                    if grid[b][a] == 0 and (a, b) not in seen:
                        seen.add((a, b))
                        pending.append((a, b))
            # The portrait cuts through the torso at the bottom, so that edge
            # is allowed. Top/side-connected white belongs to the background.
            exterior = any(xx in (0, 39) or yy == 0 for xx, yy in region)
            if len(region) >= 10 and not exterior:
                for xx, yy in region:
                    colored[yy][xx] = 1
    for y in range(40):
        for x in range(40):
            if grid[y][x] == 2 and name not in POT_FRAMES:
                if any(grid[b][a] == 3 for a, b in neighbors(x, y)):
                    colored[y][x] = 3
            # Hearts and emphasis marks above the ears use the cheek accent.
            if grid[y][x] == 1 and (y <= 12 or name in SHOCK_FRAMES):
                colored[y][x] = 2
    crop = [row[x0:x0 + width] for row in colored[y0:y0 + height]]
    return crop, colored


def encode(grid, column_major):
    width, height = len(grid[0]) // 8, len(grid) // 8
    tiles = [(x, y) for y in range(height) for x in range(width)]
    if column_major:
        tiles = [(x, y) for x in range(width) for y in range(height)]
    result = bytearray()
    for x, y in tiles:
        for row in range(8):
            pixels = grid[y * 8 + row][x * 8:x * 8 + 8]
            for plane in range(2):
                result.append(sum(((pixel >> plane) & 1) << (7 - i)
                                  for i, pixel in enumerate(pixels)))
    return bytes(result)


def generate():
    headers = (ROOT / 'src/data/pikachu/pikachu_pic_animation.asm').read_text()
    entries = re.findall(r'pikapicanimgfx\s+(-?\d+),\s+((?:Pic|GFX)_([ef][0-9a-f]+))', headers)
    assert len(entries) == 61
    output = ['; Generated by scripts/build_portraits.py; edit the generator, not these bytes.',
              'SECTION "Color Pikachu Portraits 1", ROMX, BANK[$43]', '',
              'ColorPikaGraphicHeader::',
              '\tld a, [wPikaPicAnimCurGraphicID]', '\tld l, a', '\tld h, 0',
              '\tadd hl, hl', '\tadd hl, hl', '\tld de, ColorPikaGraphicHeaders',
              '\tadd hl, de', '\tld a, [hli]', '\tld c, a', '\tld a, [hli]',
              '\tld b, a', '\tld a, [hli]', '\tld e, a', '\tld d, [hl]',
              '\tld h, b', '\tld l, c', '\tret', '',
              '; Return H=graphics bank, L=tile count, DE=tile address.',
              '; Bankswitch restores BC; HL/DE carry the result across the far call.',
              'ColorPikaGraphicHeaders:', '\tdb 0, 0, 0, 0']
    pictures = []
    for size, label, name in entries:
        crop, full = colorize(name)
        data = encode(crop, int(size) == -1)
        count = 25 if int(size) == -1 else int(size)
        assert len(data) == count * 16
        output += [f'\tdb {count}', f'\tdba Color{label}']
        pictures.append((label, name, data, full))
    used, bank = 0, 0x43
    for label, name, data, _ in pictures:
        if used + len(data) > 14500:
            bank += 1
            output += ['', f'SECTION "Color Pikachu Portraits {bank - 0x42}", ROMX, BANK[${bank:02x}]']
            used = 0
        output += ['', f'Color{label}:: ; {name}']
        for row in range(0, len(data), 16):
            output.append('\tdb ' + ', '.join(f'${byte:02x}' for byte in data[row:row + 16]))
        used += len(data)
    return '\n'.join(output) + '\n', pictures


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    assembly, pictures = generate()
    destination = ROOT / 'src/color/pikachu_graphics.asm'
    if args.check:
        assert destination.read_text() == assembly, 'Generated portrait data is stale'
    else:
        destination.write_text(assembly)
    preview = Image.new('RGB', (1280, 180 * ((len(pictures) + 7) // 8)), '#dddddd')
    draw = ImageDraw.Draw(preview)
    for i, (_, name, _, grid) in enumerate(pictures):
        image = Image.new('RGB', (40, 40))
        image.putdata([PALETTE[pixel] for row in grid for pixel in row])
        x, y = i % 8 * 160, i // 8 * 180
        draw.text((x, y), name, fill='black')
        preview.paste(image.resize((160, 160), Image.Resampling.NEAREST), (x, y + 20))
    (ROOT / 'build/verification').mkdir(parents=True, exist_ok=True)
    preview.save(ROOT / 'build/verification/portrait_assets.png')
    print(f'{len(pictures)} CGB portrait graphics generated and checked.')


if __name__ == '__main__':
    main()
